name: Run tests and package firmware
on:
  push:
    branches:
      - 'doom*'
  workflow_dispatch:

jobs:
  build:
    name: Build tx16s
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build firmware in old EdgeTX dev image
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE":/src -w /src \
            -e FLAVOR=tx16s \
            -e GITHUB_REF="$GITHUB_REF" \
            -e GITHUB_SHA="$GITHUB_SHA" \
            -e CMAKE_POLICY_VERSION_MINIMUM=3.5 \
            ghcr.io/edgetx/edgetx-dev:2.9.0 \
            ./tools/build-gh.sh
          sudo chown -R "$(id -u):$(id -g)" "$GITHUB_WORKSPACE"
          ls -la *.bin

      - name: Get DOOM1.WAD
        continue-on-error: true
        run: |
          mkdir -p DOOM
          wget -O DOOM/DOOM1.WAD https://wadhosting.com/Wad/Download/5B2E249B9C5133EC987B3EA77596381DC0D6BC1D/DOOM1.WAD

      - name: Package firmware
        uses: actions/upload-artifact@v4
        with:
          name: doom_tx16s_fw
          path: |
            LICENSE
            *.bin
            DOOM
            README.md
          retention-days: 15
          if-no-files-found: error
